version: 0.2

phases:
  install:
    commands:
      - echo 01 install phase started
      - echo no install commands defined.
      - echo install phase complete.       
  pre_build:
    commands:
      - echo 02 pre_build phase started
      - python --version
      - aws --version aws-cli
      - find . -type d
      - echo pre_build phase complete.
  build:
    commands:
      - echo 03 build phase started
      - /bin/bash upload_to_s3.sh
      - /bin/bash deploy.sh
      - echo build phase complete.
artifacts:
  files:
    - "git/**/*"