AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: update blockytime time tracking data from csv upload to s3
Parameters:
  AccountId:
    Type: String
    Description: AWS Account ID
  BlockytimeBucket:
    Type: String
    Description: S3 bucket for blockytime data
  DataPrefix:
    Type: String
    Description: S3 key event data subfolder
  DynamoDBTableName:
    Type: String
    Description: DynamoDB table to store event data
  LayerVersionSqlgsheet:
    Type: String
    Description: Layer version for the sqlgsheet package
  LayerVersionUserdata:
    Type: String
    Description: Layer version for the user data
  SourceBucket:
    Type: String
    Description: S3 bucket containing the source code
  SourceKey:
    Type: String
    Description: S3 key source code zip file
    
Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BlockytimeBucket

  EventsUpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: blockytime-events-update-cfnsam
      Description: update blockytime time tracking data from csv upload to s3
      CodeUri:
        Bucket: !Ref SourceBucket
        Key: !Ref SourceKey
      Handler: lambda_function.lambda_handler
      Runtime: python3.9  # Adjust as needed
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          S3_BUCKET: !Ref BlockytimeBucket
      Layers:
        - 'arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python39:12'
        - !Sub 
          - 'arn:aws:lambda:ap-southeast-1:${account_id}:layer:sqlgsheet:${version_sqlgsheet}'
          - version_sqlgsheet: !Ref LayerVersionSqlgsheet
            account_id: !Ref AccountId
        - !Sub 
          - 'arn:aws:lambda:ap-southeast-1:${account_id}:layer:pcl-hours-user-data:${version_userdata}'
          - version_userdata: !Ref LayerVersionUserdata
            account_id: !Ref AccountId
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BlockytimeBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTableName
      Tags:
        role: LifeHacks
        project: aws_cicd
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket: !Ref DataBucket
            Events: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref DataPrefix
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref EventsUpdateLambda
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt DataBucket.Arn